apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world  
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: kimb88/hello-world-spring-boot:latest
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /health
            port: 8080
          timeoutSeconds: 20
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 3
          failureThreshold: 5
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: dev